title = "Not a Number"
baseURL = 'https://mdodis.github.io/'
languageCode = 'en-us'
theme = "hugo-blog-awesome"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable  Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = '' # G-MEASUREMENT_ID


# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="about"
    name = 'About'
    url = '/about/'
    weight = 30

[params]
  sitename = "Not a Number"
  defaultColor = "dark" # set default color mode: dark or light
  description = "A site, about a person with a face and stuff"

[params.author]
  avatar = "BOI.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Not a Number"
  name = "Michael Dodis"
  description = "A site, about a person with a face and stuff"

[[params.socialIcons]]
name = "github"
url = "https://github.com/mdodis"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/mdodis_t"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/michael-dodis-1557141b3"

[[params.socialIcons]]
name = "itchio"
url = "https://mdodis.itch.io/"